export const API_KEYS = {
  GET_THREE_LINES: 'GET_THREE_LINES',
  GET_ONE_LINE: 'GET_ONE_LINE',
  GET_TITLE_COLOR: 'GET_TITLE_COLOR',
  GET_USER_INFO: 'GET_USER_INFO',
  SEND_LINE: 'SEND_LINE',
} as const;
